code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension bbenoist.vagrant
code --install-extension bencoleman.armview
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.docker-explorer
code --install-extension golang.go
code --install-extension googlecloudtools.cloudcode
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension IBM.output-colorizer
code --install-extension Ikuyadeu.r
code --install-extension josephtbradley.hive-sql
code --install-extension mdickin.markdown-shortcuts
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-bicep
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-node-azure-pack
code --install-extension msazurermtools.azurerm-vscode-tools
code --install-extension mshdinsight.azure-hdinsight
code --install-extension mycelo.oracle-plsql
code --install-extension p1c2u.docker-compose
code --install-extension redhat.vscode-yaml
code --install-extension scala-lang.scala
code --install-extension Shan.code-settings-sync
code --install-extension streetsidesoftware.avro
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscoss.vscode-ansible
code --install-extension xyz.plsql-language
