code --install-extension aykutsarac.jsoncrack-vscode
code --install-extension bbenoist.vagrant
code --install-extension bencoleman.armview
code --install-extension danielsanmedium.dscodegpt
code --install-extension databricks.databricks
code --install-extension dotjoshjohnson.xml
code --install-extension dvirtz.parquet-viewer
code --install-extension eamodio.gitlens
code --install-extension erd0s.terraform-autocomplete
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.docker-explorer
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension grapecity.gc-excelviewer
code --install-extension gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension ibm.output-colorizer
code --install-extension jebbs.plantuml
code --install-extension josephtbradley.hive-sql
code --install-extension kevinrose.vsc-python-indent
code --install-extension mdickin.markdown-shortcuts
code --install-extension mobiusww.vscode-dbt-databricks-power-user
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azuretools.azure-dev
code --install-extension ms-azuretools.vscode-azure-github-copilot
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurecontainerapps
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurestaticwebapps
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-bicep
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.datawrangler
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.vscode-node-azure-pack
code --install-extension msazurermtools.azurerm-vscode-tools
code --install-extension mshdinsight.azure-hdinsight
code --install-extension mycelo.oracle-plsql
code --install-extension oderwat.indent-rainbow
code --install-extension p1c2u.docker-compose
code --install-extension postman.postman-for-vscode
code --install-extension redhat.vscode-yaml
code --install-extension samuelcolvin.jinjahtml
code --install-extension scala-lang.scala
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension stevenchen.vscode-adr-manager
code --install-extension streetsidesoftware.avro
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension xyz.plsql-language
